# Generated by Django 4.2.6 on 2023-10-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_recipe_title_alter_recipe_recipe_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredient_set',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_step_list',
        ),
        migrations.RenameModel(
            old_name='recipe_step',
            new_name='RecipeStep',
        ),
        migrations.CreateModel(
            name='RecipeStepOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipestep')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(through='recipe.RecipeIngredientOrder', to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_steps',
            field=models.ManyToManyField(through='recipe.RecipeStepOrder', to='recipe.recipestep'),
        ),
    ]
